### ISSUE TITLE
Incorrect layout for wallet authorization pagef

### ISSUE THREAD

**Issue by timothywangdev** [ventureum/Chainsfr#1069]
![Screenshot from 2020-01-15 18-15-59.png](https://images.zenhubusercontent.com/5a615f3b4b5806bc2bc35c83/8ee67eea-07fb-4309-ab92-95cd06dedbc7)

https://www.figma.com/proto/aRAwRqiNglEYxZoUEeXeaC/Chainsfr_v1.2?node-id=356%3A717&viewport=-6169%2C-939%2C0.5516831278800964&scaling=min-zoom

Title -> 'Authorize'
Wallet icon missing obrder
Account name  not aligned

**Comment by InVincible2016** [comment]
This issue is not caused by component alignment. The components are aligned 'center'.
The reason is the ``Typography`` component changed line very awkwardly there.
