### ISSUE TITLE
Setup tx controller

### ISSUE THREAD

**Issue by guyuxiang** [ventureum/Chainsfr#1097]
For ethreum:
1. record the nonce of the previous transaction in the database
2. before starting the sending flow, use the recorded nonce to check if the transaction is executed or not. If not, freeze the "amount" input field.
3. if the transaction is for erc20, check both transactions.

Add instruction:
1.  Ethereum "The network is still processing your previous transaction. Please come back in 2 minutes."

![image.png](https://images.zenhubusercontent.com/5aa371cb4b5806bc2bca434b/1c9ac345-c791-466a-80b6-ac644e4f3792)

**Comment by timothywangdev** [comment]
move to release 1.1?

**Comment by timothywangdev** [comment]
a better solution is to use nonce tracker, see reference implementation https://github.com/MetaMask/metamask-extension/blob/60feeb393be5d84679dd7b94dba58540ffa166bd/app/scripts/controllers/transactions/nonce-tracker.js

**Comment by timothywangdev** [comment]
this is also causing e2e drive wallet tests failures due to unable to send next tx before previous is confirmed

**Comment by timothywangdev** [comment]
due to the complexity of nonce management, we might need to migrate the entire metamask tx controller. This will also be used in login sdk.

**Comment by timothywangdev** [comment]
alternatively, using https://github.com/MetaMask/web3-provider-engine/blob/master/subproviders/nonce-tracker.js
