### ISSUE TITLE
Receipt improvement

### ISSUE THREAD

**Issue by timothywangdev** [ventureum/Chainsfr#1101]
https://www.figma.com/file/XTQwnQ8SZGGDYo2w5nFqH9/Chainsfr_v1.3?node-id=228%3A0

**Comment by guyuxiang** [comment]
@InVincible2016 
https://www.figma.com/file/RyUFKRtmnRVYpyLlMyAWi883/Chainsfer?node-id=891%3A1

**Comment by guyuxiang** [comment]
![image](https://user-images.githubusercontent.com/37234721/74164064-454b8480-4bf1-11ea-8713-29164fe7bd1f.png)
https://www.figma.com/file/XTQwnQ8SZGGDYo2w5nFqH9/Chainsfr_v1.3?node-id=437%3A0

@InVincible2016 the finished desigh is here.
