### ISSUE TITLE
Receive flow UI redesign

### ISSUE THREAD

**Issue by timothywangdev** [ventureum/Chainsfr#1160]
logout page
![Screenshot from 2020-02-11 14-15-21.png](https://images.zenhubusercontent.com/5a615f3b4b5806bc2bc35c83/4352c8db-bb79-43a0-a1d9-774b687a2a5f)!

login page
[Screenshot from 2020-02-11 14-13-49.png](https://images.zenhubusercontent.com/5a615f3b4b5806bc2bc35c83/bc474310-83fb-4fe5-9493-ccdb6f4b2f40)

review page
![Screenshot from 2020-02-11 14-15-21.png](https://images.zenhubusercontent.com/5a615f3b4b5806bc2bc35c83/0f6a6c96-83fa-4b23-8ed0-422486b151ff)

Need to be consistent with send flow

**Comment by guyuxiang** [comment]
![image](https://user-images.githubusercontent.com/37234721/74286420-b83e2380-4cf5-11ea-8978-20a09d5e580a.png)
