### ISSUE TITLE
Wallet page major redesign

### ISSUE THREAD

**Issue by timothywangdev** [ventureum/Chainsfr#1196]
https://www.figma.com/file/XTQwnQ8SZGGDYo2w5nFqH9/Chainsfr_v1.3?node-id=828%3A1487

**Comment by timothywangdev** [comment]
https://www.figma.com/file/XTQwnQ8SZGGDYo2w5nFqH9/Chainsfr_v1.3?node-id=828%3A1487

**Comment by guyuxiang** [comment]
https://www.figma.com/proto/XTQwnQ8SZGGDYo2w5nFqH9/Chainsfr_v1.3?node-id=936%3A25&viewport=94%2C-589%2C0.3575584888458252&scaling=min-zoom
