### ISSUE TITLE
Crypto icon set change

### ISSUE THREAD

**Issue by guyuxiang** [ventureum/Chainsfr#1198]
change the gradient color style to flat solid color style

**Comment by williamleha** [comment]
![image.png](https://images.zenhubusercontent.com/5c9032eed06a4e6d359ed46b/7a5cd5be-4f64-4811-a1b5-3984077faeef)

![image.png](https://images.zenhubusercontent.com/5c9032eed06a4e6d359ed46b/0c86c917-7931-4ce3-ab15-992626350e8f)
