### ISSUE TITLE
Robustness enhancement of transfer execution

### ISSUE THREAD

**Issue by guyuxiang** [ventureum/Chainsfr#1202]
To make the transfer execution more robust in case of unstable internet connection,

- send non-sensitive transfer data to chainsfr back-end before sending the transaction to the blockchain network.
- create transfer ID before broadcasting
- enhancement in chainsfr backend as well

**Comment by timothywangdev** [comment]
1. support dryrun option in transfers
    - send
      - get txHash from txObj on client side
    - receive/cancel
      - get txHash from txObj on server side, pass back to client
