### ISSUE TITLE
Btc transfer validate failure

### ISSUE THREAD

**Issue by timothywangdev** [ventureum/Chainsfr#1208]
![Screenshot from 2020-02-25 14-09-45.png](https://images.zenhubusercontent.com/5a615f3b4b5806bc2bc35c83/09608716-58ce-4b8b-bbbe-d334aff4d42e)

![Screenshot from 2020-02-25 14-10-13.png](https://images.zenhubusercontent.com/5a615f3b4b5806bc2bc35c83/0a2cf186-5b56-487e-832e-99fadff82f28)

successfully sent but validation failed

https://blockstream.info/testnet/tx/58792bd67ad13118064f8c38546896edc5f8a73d67f27769099b268f13100045

https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=/aws/lambda/LambdaValidateTxTest;stream=2020/02/25/[$LATEST]79b13e7d1b32496d945350f36d1da07f;start=2020-02-24T18:45:32Z

**Comment by InVincible2016** [comment]
This seems to be a back-end problem.
