### ISSUE TITLE
Better google sign-in button

### ISSUE THREAD

**Issue by guyuxiang** [ventureum/Chainsfr#1211]

**Comment by williamleha** [comment]
![image.png](https://images.zenhubusercontent.com/5c9032eed06a4e6d359ed46b/0859d15b-3946-48d8-8ad3-f7bec794307d)

https://www.figma.com/file/WpiTyjUFCbSpROz3YdvJPx/Chainsfr-Components?node-id=4%3A0

**Comment by guyuxiang** [comment]
@InVincible2016
