### ISSUE TITLE
Login page improvement

### ISSUE THREAD

**Issue by guyuxiang** [ventureum/Chainsfr#1218]
- new instruction on the login page
- put content in the center of both half pages.

**Comment by timothywangdev** [comment]
status of this?

**Comment by guyuxiang** [comment]
@williamleha

**Comment by timothywangdev** [comment]
no response, close for now

**Comment by guyuxiang** [comment]
lezhong are working on it.

**Comment by timothywangdev** [comment]
@williamleha 

![Screenshot from 2020-03-30 16-44-55.png](https://images.zenhubusercontent.com/5a615f3b4b5806bc2bc35c83/45cc498a-d922-4576-acc3-0cb8c28dcb64)

adjust the background color to make it consistent with test stage (dark blue)

**Comment by timothywangdev** [comment]
@williamleha is this done?
