### ISSUE TITLE
[Test] Accounts management

### ISSUE THREAD

**Issue by timothywangdev** [ventureum/Chainsfr#1231]
1. create/delete/modify account
2. address qr code modal
4. account sync (eth)
5. account sync (btc)
6. Use reduxTracker to ensure actions are fulfilled and no error snackbars showed

**Comment by InVincible2016** [comment]
- stop at third party wallet connect

**Comment by InVincible2016** [comment]
- unable to add Coinbase account due to SMS text verification upon login
