### ISSUE TITLE
Show all supported wallet and coin type model/button on "transfer"/home page

### ISSUE THREAD

**Issue by guyuxiang** [ventureum/Chainsfr#1242]
https://help.chainsfr.com/en/articles/3809286

Use a link to show the faq page in opened Intercom Messenger.
Use the intercom (custom_launcher_selector) feature can do the job.

 Check the following guide for details:
https://www.intercom.com/help/en/articles/2894-customize-the-intercom-messenger-technical

**Comment by timothywangdev** [comment]
this is done

**Comment by guyuxiang** [comment]
nope

**Comment by timothywangdev** [comment]
add account already shown

**Comment by williamleha** [comment]
![image.png](https://images.zenhubusercontent.com/5c9032eed06a4e6d359ed46b/7a47623c-27ff-432d-a8dc-15e5111292af)

**Comment by InVincible2016** [comment]
- Issue outdated. Close as instructed.
