### ISSUE TITLE
Add acount redesign

### ISSUE THREAD

**Issue by timothywangdev** [ventureum/Chainsfr#1254]
https://www.figma.com/proto/XTQwnQ8SZGGDYo2w5nFqH9/Chainsfr_v1.3?node-id=1244%3A5024&scaling=min-zoom

**Comment by guyuxiang** [comment]
https://www.figma.com/file/RyUFKRtmnRVYpyLlMyAWi883/Chainsfr_Lucas?node-id=1303%3A0
