### ISSUE TITLE
Instruction text cleaning

### ISSUE THREAD

**Issue by guyuxiang** [ventureum/Chainsfr#1310]
- first section text.
- sending flow text.

**Comment by timothywangdev** [comment]
1. remove landing page subtitle
2. remove contact page subtitle
3. edit setting page security tab
    ```
    waiting for content...
    ```

**Comment by timothywangdev** [comment]
updates by @guyuxiang 

1. landing page subtitle change to

```
Send Crypto payment to any Email address. No more cryptic address.
```

2. wallet page subtitle change to

```
Transfer fund between Chainsfr wallet and your connected accounts.
```

3. account page subtitle change to

```
Native supports for popular exchanges, mobile and hardware wallets
```
