### ISSUE TITLE
profile photo display bug

### ISSUE THREAD

**Issue by guyuxiang** [ventureum/Chainsfr#1341]
Two problems here:
1. the receiver is a registered user, so there should be a user profile photo
2. even the user profile photo is not shown, it should be the first letter of user name, not the placeholder

![image.png](https://images.zenhubusercontent.com/5aa371cb4b5806bc2bca434b/64868b20-4ae4-4928-80f9-5ae9056c45ca)

**Comment by timothywangdev** [comment]
Suggest gathering and updating recipient imageUrl during getRecipients at the backend

**Comment by timothywangdev** [comment]
existing approach causing lots of "user not found" api errors

**Comment by timothywangdev** [comment]
same problem also exists on review, receipt pages
