### ISSUE TITLE
Review avatars not aligned vertically

### ISSUE THREAD

**Issue by guyuxiang** [ventureum/Chainsfr#1343]
1. the alignment seems to be off

![image.png](https://images.zenhubusercontent.com/5aa371cb4b5806bc2bca434b/1106b98c-2659-41fc-873b-c9d154ec8e0a)

**Comment by guyuxiang** [comment]
same for transaction history

![image.png](https://images.zenhubusercontent.com/5aa371cb4b5806bc2bca434b/5aa1e7ce-902f-4d0a-ae5e-2df45bab0f9a)

**Comment by timothywangdev** [comment]
these are three separate issues

**Comment by timothywangdev** [comment]
transfer history avatar is fixed by #1341

**Comment by timothywangdev** [comment]
review avatar is fixed by #1341
