### ISSUE TITLE
container moving when clicking on dots

### ISSUE THREAD

**Issue by guyuxiang** [ventureum/Chainsfr#1348]
![image.png](https://images.zenhubusercontent.com/5aa371cb4b5806bc2bca434b/43f471bd-9bd7-453b-8f78-02a592fd0132)

**Comment by timothywangdev** [comment]
@guyuxiang unable to reproduce

**Comment by timothywangdev** [comment]
reproduced by using full screen

**Comment by timothywangdev** [comment]
removing tooltip seems to fix the problem
