### ISSUE TITLE
Add instruction text when adding account

### ISSUE THREAD

**Issue by guyuxiang** [ventureum/Chainsfr#1374]
![image.png](https://images.zenhubusercontent.com/5aa371cb4b5806bc2bca434b/91695af7-df14-4106-9ead-bf3e8fca8173)
- indicate if every account can deposit or send, only get public address
- show all account type but grey the disabled ones and indicate is can be added on desktop
![image.png](https://images.zenhubusercontent.com/5aa371cb4b5806bc2bca434b/763d9331-6cf8-42e0-84f9-7d2a665beb16)
- on the last page to save the added account, indicate again what can be done with the account, send/receive etc, easy to deposit when receiving fund

**Comment by timothywangdev** [comment]
![Screenshot from 2020-04-20 15-37-58.png](https://images.zenhubusercontent.com/5a615f3b4b5806bc2bc35c83/c6ed111c-facc-4530-b876-229c35e16d04)

Also show disable reason for account dropdown

**Comment by guyuxiang** [comment]
https://www.figma.com/file/RyUFKRtmnRVYpyLlMyAWi883/Chainsfr_Lucas?node-id=1486%3A0
@InVincible2016

**Comment by timothywangdev** [comment]
@guyuxiang no space on the Right side of account dropdown

**Comment by InVincible2016** [comment]
![Screen Shot 2020-04-26 at 3.32.17 PM.png](https://images.zenhubusercontent.com/5ad6409c4b5806bc2bcf7ee2/b74c0dc1-c8bd-4cc3-9e79-794c5ea9e63e)

This part was not able to be done due to the 'p' element on the right can't wrap properly inside select

**Comment by timothywangdev** [comment]
@guyuxiang @InVincible2016  cannot use right side, move error message to a new line

**Comment by guyuxiang** [comment]
OK👌
