### ISSUE TITLE
Windows webusb instruction

### ISSUE THREAD

**Issue by timothywangdev** [ventureum/Chainsfr#1402]
https://www.npmjs.com/package/@ledgerhq/hw-transport-webusb

**Comment by guyuxiang** [comment]
"How to Install" is a null link for intercom launcher trigger, which will be set up in Intercom later.

![image.png](https://images.zenhubusercontent.com/5aa371cb4b5806bc2bca434b/098c617a-e64e-4c5f-bbb0-ee04fdefe2a3)

**Comment by timothywangdev** [comment]
@guyuxiang @williamleha status of  design?

**Comment by guyuxiang** [comment]
Remove "I DID IT"
