### ISSUE TITLE
Bitcoin account network error notification inappropriate

### ISSUE THREAD

**Issue by timothywangdev** [ventureum/Chainsfr#1439]
![Screenshot from 2020-04-07 14-32-51.png](https://images.zenhubusercontent.com/5a615f3b4b5806bc2bc35c83/d7910122-971f-4dbc-8280-e9d8bfe1a97d)

Choose bitcoin mainnet on ledger and start a transfer

**Comment by InVincible2016** [comment]
Please write down how to reproduce...

**Comment by timothywangdev** [comment]
fixed
