### ISSUE TITLE
Error message of multiple opened sessions, once one session log out

### ISSUE THREAD

**Issue by guyuxiang** [ventureum/Chainsfr#1624]
When multiple sessions are opened and logged in at the same time, once the user manually log out one of the sessions, and then go to another opened session, there will be several error messages showing up.

Find a way to identify the situation without showing the error messages. And consider automatically refresh the opened sessions.

**Comment by InVincible2016** [comment]
- This seems to be the result of the redux login state not being synced across all tabs.
