### ISSUE TITLE
Decrypt and export drive data

### ISSUE THREAD

**Issue by guyuxiang** [ventureum/Chainsfr#1647]
Design to be added.

Add button to export data.

**Comment by timothywangdev** [comment]
@guyuxiang design needed

**Comment by guyuxiang** [comment]
@InVincible2016 
https://www.figma.com/file/iXF0PWGB77ibA9mygIrLOC/Chainsfr_lucas_2?node-id=85%3A0

design updated.

**Comment by guyuxiang** [comment]
New design  @InVincible2016 

https://www.figma.com/file/iXF0PWGB77ibA9mygIrLOC/Chainsfr_lucas_2?node-id=134%3A0
