### ISSUE TITLE
Add 404 page

### ISSUE THREAD

**Issue by guyuxiang** [ventureum/Chainsfr#1649]

**Comment by timothywangdev** [comment]
use this style: https://material-ui.com/getting-started/templates/dashboard/asd

**Comment by guyuxiang** [comment]
https://www.figma.com/file/iXF0PWGB77ibA9mygIrLOC/Chainsfr_lucas_2?node-id=55%3A0
@InVincible2016

**Comment by guyuxiang** [comment]
Updated.
