### ISSUE TITLE
Improvement on "Add connection" button in sending flow

### ISSUE THREAD

**Issue by guyuxiang** [ventureum/Chainsfr#1651]
The button will redirect to "connections" page. 

https://www.figma.com/file/iXF0PWGB77ibA9mygIrLOC/Chainsfr_lucas_2?node-id=29%3A0

**Comment by timothywangdev** [comment]
@InVincible2016 The add connection btn remains the same in receive flow, otherwise user has to re-click email link from inbox after adding a new connection
