### ISSUE TITLE
Investigate feasibility of Firefox

### ISSUE THREAD

**Issue by timothywangdev** [ventureum/Chainsfr#1773]
check if the following wallets are supported:
1. Metamask
2. Ledger
3. WalletConnect
4. WalletLink
5. Chainsfr Wallet

make a transfer and check the status

Modify wallets.js when necessary

**Comment by timothywangdev** [comment]
metamask works

**Comment by InVincible2016** [comment]
Need to disable ledger 'send' and 'add', 'receive' is working

**Comment by timothywangdev** [comment]
using metamask to connect ledger then send works

**Comment by InVincible2016** [comment]
Metamask mobile works

**Comment by InVincible2016** [comment]
Coinbase ETH and BTC 'add' works

**Comment by InVincible2016** [comment]
Coinbase WalletLink works both send and add
