### ISSUE TITLE
Accept ERC20 token with Metamask wallet error

### ISSUE THREAD

**Issue by InVincible2016** [ventureum/Chainsfr#569]
- Make an ERC20 transfer
- Accept the transfer.
- In the wallet selection page, select Metamask, press continue. and the following is shown
![Screen Shot 2019-06-24 at 3.11.17 PM.png](https://images.zenhubusercontent.com/5ad6409c4b5806bc2bcf7ee2/30214a20-bf12-4999-8a66-e5be85c63c5c)

**Comment by timothywangdev** [comment]
Resolved by issue #568
