### ISSUE TITLE
1.0 Beta Release

### ISSUE THREAD

**Issue by timothywangdev** [ventureum/Chainsfr#620]

**Comment by guyuxiang** [comment]
🔗 **Lucas Gu** just linked this issue to a Userfeed post:

> Version 1.0 Release

[View post in Userfeed →](https://www.userfeed.io/permalink/orgs/f9228baf-e79c-484c-abf6-147ffdf800e2/posts/4a27c033-24ff-4f26-ba4a-4d8d5cea58c1)
