### ISSUE TITLE
Add "fiat money" amount in transactions and balance

### ISSUE THREAD

**Issue by guyuxiang** [ventureum/Chainsfr#654]
We want to let users easily track the transaction value in terms of fiat currencies.

- add **fiat price source api**, eg. coinmarketcap or some crypto exchanges
- for every transaction we might need to record a few more data fields in ourt database, **fiat amount**, **fiat currency**, **historic exchange rate/price (at the time of the transaction)**, **fiat price api source**.
- for wallet balance add an api call to show the current fiat balance.
- UI changes according to this feature

**Comment by timothywangdev** [comment]
not included in 1.0 release

**Comment by guyuxiang** [comment]
This is a separate epic.

**Comment by timothywangdev** [comment]
duplicated
