### ISSUE TITLE
Notify emails untrusted

### ISSUE THREAD

**Issue by InVincible2016** [ventureum/Chainsfr#657]
- Notify emails that are sent to external domain email addresses are filter into 'Spam/Junk' email folder in the recipient's email. See screenshot below:
![Screen Shot 2019-07-17 at 2.38.46 PM.png](https://images.zenhubusercontent.com/5ad6409c4b5806bc2bcf7ee2/50ed2ae4-a0cd-48ae-804f-1348054f8d3f)

- The link that is composed in the notify email is currently being recognized as suspicious link. See screenshot below:
![Screen Shot 2019-07-17 at 3.16.42 PM.png](https://images.zenhubusercontent.com/5ad6409c4b5806bc2bcf7ee2/77b22118-a4dd-4345-bf11-f82eaafd74ce)

**Comment by timothywangdev** [comment]
Setup DKIM, SP SMARC successfully.

**Comment by timothywangdev** [comment]
Send raw message from ses with the following content passed:

```
Hi wanghujieus@gmail.com,

wanghujie@gmail.com just sent you 1 DAI.

The transfer was sent by wanghujie@gmail.com on Jul 17th 2019, 20:46:09 pm (UTC)
To accept or review details of this transfer, please click on the button below to receive it.

Deposite your DAI: https://testnet.chainsfr.com


```

**Comment by timothywangdev** [comment]
requested two dedicated ip for aws email server
