### ISSUE TITLE
Review and improve on snackbar coloring

### ISSUE THREAD

**Issue by guyuxiang** [ventureum/Chainsfr#686]
Currently, many snackbar notifications are in red, e.g. "Invalid password", which should not be red.

1. Review all snack bar messages.
2. Redesign and improve warnings.

**Comment by williamleha** [comment]
![image.png](https://images.zenhubusercontent.com/5c9032eed06a4e6d359ed46b/98ad4492-d978-4741-a7fa-99390924c5f5)

![image.png](https://images.zenhubusercontent.com/5c9032eed06a4e6d359ed46b/e52f3cc5-cb2f-451e-bca4-3b176429888f)

**Comment by williamleha** [comment]
[Uploading... image.png ]

**Comment by InVincible2016** [comment]
No longer an issue
