### ISSUE TITLE
Collective enhancement of FAQ (#1 before beta release)

### ISSUE THREAD

**Issue by guyuxiang** [ventureum/Chainsfr#689]
There is a list of enhancement of FAQ that comes from user testing summary. (not completed yet)

1. Add cancellation time in the FAQ.
2. Email notification wait-time instructions, including all situations of senders and receivers.
3. Emphasis users that they can use any emails to get notifications but will need a google account to deposit the money.
4. 
5. Better organization of information. Put the most important information at the beginning. make users easier to read through.
6.

**Comment by timothywangdev** [comment]
what's the status if this issue?

**Comment by timothywangdev** [comment]
Completed the following sections

![Screenshot from 2019-12-23 20-27-32.png](https://images.zenhubusercontent.com/5a615f3b4b5806bc2bc35c83/776304d0-0600-42a3-9b06-16c8d063b046)
