### ISSUE TITLE
Introduce offline error page

### ISSUE THREAD

**Issue by guyuxiang** [ventureum/Chainsfr#696]
Design and implement a test for every in-app pages. If there is a local network error, then freeze all functions on the page and popup an instruction (using model or snack bar or other message styles).

Here are examples:
![image.png](https://images.zenhubusercontent.com/5aa371cb4b5806bc2bca434b/e5184fdc-502c-4e18-8486-ab05771a10ab)
![image.png](https://images.zenhubusercontent.com/5aa371cb4b5806bc2bca434b/94caf521-7c4f-4015-93da-350afd9f3bfa)

![image.png](https://images.zenhubusercontent.com/5aa371cb4b5806bc2bca434b/598220c5-7d3b-43a2-a2f5-d2aaa432275f)

![image.png](https://images.zenhubusercontent.com/5aa371cb4b5806bc2bca434b/49299966-5243-4a38-ba11-58fff75cf94d)

![image.png](https://images.zenhubusercontent.com/5aa371cb4b5806bc2bca434b/87b08ef3-d49c-4f80-a633-03de542d6437)

**Comment by timothywangdev** [comment]
should this be in 1.0?
