### ISSUE TITLE
Add links to Ventureum.io pages

### ISSUE THREAD

**Issue by guyuxiang** [ventureum/Chainsfr#706]
The chainsfr.com page should mention Ventureum.io and have links to ventureum.io, probably in the footnote.

**Comment by guyuxiang** [comment]
@williamleha This one needs to be designed and added in the footnote.

**Comment by williamleha** [comment]
![image.png](https://images.zenhubusercontent.com/5c9032eed06a4e6d359ed46b/34797ebd-d681-42ac-9d8e-5303cd88e8ee)
