### ISSUE TITLE
Put "Unlock wallet" right before confirming a transaction  

### ISSUE THREAD

**Issue by guyuxiang** [ventureum/Chainsfr#711]
In most mobile payment experience, inputting "payment password" or "fingerprint verification" is usually the last step of payment, which decreases the possibility of security issues.

**Comment by timothywangdev** [comment]
maybe not 1.0?

**Comment by guyuxiang** [comment]
Agree. And it is in backlog. lolll

**Comment by InVincible2016** [comment]
Fixed
