### ISSUE TITLE
Add "expired" and "reclaimed" status for transactions

### ISSUE THREAD

**Issue by guyuxiang** [ventureum/Chainsfr#753]
more to add

**Comment by guyuxiang** [comment]
1. add "expired" and "reclaimed" status in backend
2. show "expired" or "reclaimed" status in the transaction history
3. add "expiration details" in each transaction details(transaction history)  
4. add "expiration details" in each transaction details page

**Comment by guyuxiang** [comment]
@timothywangdev This one is done, right?

**Comment by timothywangdev** [comment]
![Screenshot from 2020-03-12 15-08-40.png](https://images.zenhubusercontent.com/5a615f3b4b5806bc2bc35c83/da45df4b-dafd-432e-93a7-5ebc82e4d5cd)

![Screenshot from 2020-03-12 15-08-23.png](https://images.zenhubusercontent.com/5a615f3b4b5806bc2bc35c83/1f167805-48be-48c8-8a2c-969f2ee8f2fe)

![Screenshot from 2020-03-12 15-06-18.png](https://images.zenhubusercontent.com/5a615f3b4b5806bc2bc35c83/663e4e67-4ae7-4f9e-81c7-08dcb4065364)
