### ISSUE TITLE
Support more ERC20

### ISSUE THREAD

**Issue by guyuxiang** [ventureum/Chainsfr#761]
**The following coin will be added after discussion**
USDT
https://etherscan.io/token/0xdac17f958d2ee523a2206206994597c13d831ec7

USDC
https://etherscan.io/token/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48

TUSD
https://etherscan.io/token/0x0000000000085d4780B73119b644AE5ecd22b376
___
**The following coin will NOT be added at current state**
BNB
https://etherscan.io/token/0xB8c77482e45F1F44dE1745F52C74426C631bDD52

LEO
https://etherscan.io/token/0x2af5d2ad76741191d15dfe7bf6ac92d4bd912ca3

HT
https://etherscan.io/token/0x6f259637dcd74c767781e37bc6133cd6a68aa161

LINK
https://etherscan.io/token/0x514910771af9ca656af840dff83e8264ecf986ca

MKR
https://etherscan.io/token/0x9f8f72aa9304c8b593d555f12ef6589cc3a579a2

CRO
https://etherscan.io/token/0xa0b73e1ff0b80914ab6fe0444e65848c4c34450b

OKB
https://etherscan.io/token/0x75231f58b43240c9718dd58b4967c5114342a86c

BAT
https://etherscan.io/token/0x0d8775f648430679a709e98d2b0cb6250d2887ef

REP
https://etherscan.io/token/0x1985365e9f78359a9B6AD760e32412f4a445E862

ZRX
https://etherscan.io/token/0xe41d2489571d322189246dafa5ebde1f4699f498

KNC
https://etherscan.io/token/0xdd974d5c2e2928dea5f71b9825b8b646686bd200

WBTC
https://etherscan.io/token/0x2260fac5e5542a773aa44fbcfedf7c193bc2c599

**Comment by timothywangdev** [comment]
usdt is not erc20

**Comment by guyuxiang** [comment]
> usdt is not erc20

It is.
https://etherscan.io/token/0xdac17f958d2ee523a2206206994597c13d831ec7

**Comment by timothywangdev** [comment]
Add usdt, usdc only to test stability
