### ISSUE TITLE
TransferFormComponent UI improvement 

### ISSUE THREAD

**Issue by InVincible2016** [ventureum/Chainsfr#778]
![Screen Shot 2019-08-28 at 11.31.01 AM.png](https://images.zenhubusercontent.com/5ad6409c4b5806bc2bcf7ee2/22f4f401-04b5-4900-bf15-3e62908c7399)

**Comment by timothywangdev** [comment]
> 要不我们改成random按钮放在input内，用那个inputadorment；add recipient加在dropdown最后一个选项，text button触发dialog？
<sub>[View in Slack](https://ventureum-team.slack.com/archives/DA80DGUVD/p1567710944000800)</sub>
