### ISSUE TITLE
Improvement on Email templates

### ISSUE THREAD

**Issue by guyuxiang** [ventureum/Chainsfr#784]
1. cancel_action_sender_notification.html email is for sender's actions  of canceling before expiration and reclaiming after expiration. Improving the wording to make it more consistent for both cases.
2. add dollar sign to all fiat money occasions. 
3. change footnote text alignment to left.
4. wording improvement on the expiration period instruction of all occasions.

**Comment by timothywangdev** [comment]
need updates on #1
