### ISSUE TITLE
Bug: creating a new ChainsfrData folder every time after deleting drive data

### ISSUE THREAD

**Issue by guyuxiang** [ventureum/Chainsfr#859]
After deleting the chainsfr drive app data and recreating a chainsfr account, there will be a new ChainsfrData folder in the google drive.

![image.png](https://images.zenhubusercontent.com/5aa371cb4b5806bc2bca434b/9cb0b671-bc5e-45fd-822e-ac8dc2508cee)

**Comment by timothywangdev** [comment]
delete op works properly.
disconnect causes the problem due to the previous created folder no longer belong to the app.
